import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Headers from "@/components/Headers";
import { Box } from "@mui/material";
import { PropertyProvider } from "@/contexts/PropertyContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PropertyProvider>
          <Box
            sx={{ width: "100vw", height: "100vh", backgroundColor: "black" }}
          >
            <Headers />
            {children}
          </Box>
        </PropertyProvider>
      </body>
    </html>
  );
}
